server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${JDBC_URL:jdbc:mysql://localhost:3306/your_database_name?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai}
    username: ${JDBC_USERNAME:your_username}
    password: ${JDBC_PASSWORD:your_password}
  
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Claude API配置
claude:
  api:
    url: ${CLAUDE_API_URL:https://api.anthropic.com/v1/messages}
    key: ${CLAUDE_API_KEY:your_api_key}
    model: ${CLAUDE_API_MODEL:claude-3-opus-20240229}
    max-tokens: ${CLAUDE_MAX_TOKENS:4096}
    temperature: ${CLAUDE_TEMPERATURE:0.7}

# 文件存储配置
storage:
  upload-dir: ${UPLOAD_DIR:./uploads}
  temp-dir: ${TEMP_DIR:./temp}

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.aiconvert.entity
  configuration:
    map-underscore-to-camel-case: true

# 日志配置
logging:
  level:
    root: ${LOG_LEVEL:INFO}
    com.aiconvert: ${APP_LOG_LEVEL:DEBUG}
  file:
    path: ${LOG_PATH:./logs}
    name: ${LOG_FILE:./logs/application.log} 